import json
from pathlib import Path

import pytest

from baselines.t2_langgraph.adapter import (
    T2Config,
    build_t2_tools,
    generate,
)
from common.skill_adapter import SkillAdapter
from common.task_schema import TaskSpec


def _task() -> TaskSpec:
    return TaskSpec.from_dict(
        {
            "task_id": "t2-test",
            "bridge_type": "cantilever_box",
            "task_form": "whole",
            "difficulty": "L1",
            "natural_language_requirement": "build a bridge model",
        }
    )


def _skills(tmp_path: Path) -> SkillAdapter:
    root = tmp_path / "skills"
    (root / "osis-project").mkdir(parents=True)
    (root / "osis-project" / "SKILL.md").write_text(
        "---\nname: OSIS project\ndescription: build models\n---\nUse pyosis.",
        encoding="utf-8",
    )
    return SkillAdapter(root)


def test_t2_defaults_to_the_frozen_model(monkeypatch: pytest.MonkeyPatch):
    monkeypatch.delenv("OSIS_MODEL_ID", raising=False)
    monkeypatch.delenv("OSIS_MODEL_BASE_URL", raising=False)
    config = T2Config.from_env(api_key="test-key")
    assert config.model == "deepseek-v4.1-flash-expires-on-0910"
    assert config.base_url == "http://47.92.150.231/v1"
    assert config.api_key == "test-key"


def test_t2_write_tool_rejects_paths_outside_candidate(tmp_path: Path):
    tools = build_t2_tools(tmp_path / "candidate", _skills(tmp_path))
    write_file = next(tool for tool in tools if tool.name == "write_file")
    result = write_file.invoke({"relative_path": "../escape.py", "content": "bad"})
    assert result.startswith("TOOL_ERROR:")
    assert "outside candidate workspace" in result
    assert not (tmp_path / "escape.py").exists()


def test_t2_write_tool_allows_absolute_path_inside_candidate(tmp_path: Path):
    candidate = tmp_path / "candidate"
    tools = build_t2_tools(candidate, _skills(tmp_path))
    write_file = next(tool for tool in tools if tool.name == "write_file")
    absolute = candidate / "py" / "prep" / "inside.py"
    write_file.invoke({"relative_path": str(absolute), "content": "ok"})
    assert absolute.read_text(encoding="utf-8") == "ok"


def test_t2_missing_reference_is_a_recoverable_tool_result(tmp_path: Path):
    tools = build_t2_tools(tmp_path / "candidate", _skills(tmp_path))
    read_reference = next(tool for tool in tools if tool.name == "read_skill_reference")
    result = read_reference.invoke(
        {"skill_id": "osis-project", "relative_path": "references/missing.md"}
    )
    assert result.startswith("TOOL_ERROR:")
    assert "missing.md" in result


def test_t2_generate_runs_langgraph_react_and_writes_candidate(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    responses = [
        {
            "choices": [
                {
                    "message": {
                        "role": "assistant",
                        "content": "",
                        "tool_calls": [
                            {
                                "id": "call-1",
                                "type": "function",
                                "function": {
                                    "name": "write_file",
                                    "arguments": json.dumps(
                                        {
                                            "relative_path": "py/prep/main.py",
                                            "content": "# generated by test\n",
                                        }
                                    ),
                                },
                            }
                        ],
                    }
                }
            ],
            "usage": {
                "prompt_tokens": 100,
                "completion_tokens": 20,
                "total_tokens": 120,
            },
        },
        {
            "choices": [
                {
                    "message": {
                        "role": "assistant",
                        "content": "Candidate project written.",
                    }
                }
            ],
            "usage": {
                "prompt_tokens": 140,
                "completion_tokens": 8,
                "total_tokens": 148,
            },
        },
    ]

    class FakeResponse:
        status_code = 200
        headers = {"content-type": "application/json"}

        def __init__(self, body):
            self._body = body
            self.text = json.dumps(body)

        def raise_for_status(self):
            return None

        def json(self):
            return self._body

    calls = []

    def fake_post(*args, **kwargs):
        calls.append((args, kwargs))
        return FakeResponse(responses.pop(0))

    monkeypatch.setattr("baselines.t2_langgraph.adapter.requests.post", fake_post)
    workspace = tmp_path / "workspace"
    candidate = generate(
        _task(),
        _skills(tmp_path),
        workspace,
        config=T2Config.from_env(api_key="test-key", max_steps=4),
    )

    assert candidate == workspace / "candidate_project"
    assert (candidate / "py" / "prep" / "main.py").read_text(encoding="utf-8") == (
        "# generated by test\n"
    )
    metadata = json.loads((workspace / "t2_generation.json").read_text(encoding="utf-8"))
    assert metadata["status"] == "completed"
    assert metadata["model"] == "deepseek-v4.1-flash-expires-on-0910"
    assert metadata["tool_calls"] == 1
    assert metadata["tokens"] == {
        "input_tokens": 240,
        "output_tokens": 28,
        "reasoning_tokens": 0,
        "cache_read_tokens": 0,
        "total_tokens": 268,
    }
    assert len(calls) == 2
    assert calls[0][1]["json"]["model"] == "deepseek-v4.1-flash-expires-on-0910"
    assert "test-key" not in (workspace / "t2_generation.json").read_text(encoding="utf-8")


def test_t2_generate_writes_react_transcript(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    write_call = {
        "id": "call-1",
        "type": "function",
        "function": {
            "name": "write_file",
            "arguments": json.dumps(
                {"relative_path": "py/prep/main.py", "content": "# generated by test\n"}
            ),
        },
    }
    responses = [
        {
            "choices": [
                {"message": {"role": "assistant", "content": "", "tool_calls": [write_call]}}
            ]
        },
        {
            "choices": [
                {"message": {"role": "assistant", "content": "Candidate project written."}}
            ]
        },
    ]

    class FakeResponse:
        status_code = 200
        headers = {"content-type": "application/json"}

        def __init__(self, body):
            self._body = body
            self.text = json.dumps(body)

        def raise_for_status(self):
            return None

        def json(self):
            return self._body

    monkeypatch.setattr(
        "baselines.t2_langgraph.adapter.requests.post",
        lambda *args, **kwargs: FakeResponse(responses.pop(0)),
    )
    workspace = tmp_path / "workspace"
    generate(
        _task(),
        _skills(tmp_path),
        workspace,
        config=T2Config.from_env(api_key="test-key", max_steps=4),
    )

    lines = [
        json.loads(line)
        for line in (workspace / "t2_transcript.jsonl")
        .read_text(encoding="utf-8")
        .splitlines()
    ]
    assert [record["role"] for record in lines] == ["user", "ai", "ai"]
    write_step = lines[1]
    assert write_step["model_called_tool"] is True
    call = write_step["tool_calls"][0]
    assert call["name"] == "write_file"
    assert call["args"]["relative_path"] == "py/prep/main.py"
    expected_return = f"wrote py/prep/main.py ({len('# generated by test\n')} chars)"
    assert call["return"]["chars"] == len(expected_return)
    assert call["return"]["sha256"]
    assert call["return"]["head"] == expected_return
    final_step = lines[2]
    assert final_step["model_called_tool"] is False
    assert final_step["final_text"] == "Candidate project written."


def test_t2_transcript_records_invalid_tool_calls_and_finish_reason(tmp_path: Path):
    from langchain_core.messages import AIMessage

    from baselines.t2_langgraph.adapter import _TranscriptWriter

    message = AIMessage(
        content="",
        tool_calls=[{"name": "write_file", "args": {"relative_path": "a.py"}, "id": "c1"}],
        invalid_tool_calls=[
            {
                "name": "write_file",
                "args": '{"relative_path": "E:\\\\bad.py"',
                "error": "malformed arguments",
                "id": "c2",
            }
        ],
        response_metadata={"finish_reason": "tool_calls", "usage": {"prompt_tokens": 10}},
    )
    path = tmp_path / "t2_transcript.jsonl"
    writer = _TranscriptWriter(path)
    writer.add_message(message)
    writer.close()

    record = json.loads(path.read_text(encoding="utf-8").splitlines()[0])
    assert record["finish_reason"] == "tool_calls"
    assert record["usage"] == {"prompt_tokens": 10}
    assert record["tool_calls"][0]["name"] == "write_file"
    invalid = record["invalid_tool_calls"][0]
    assert invalid["name"] == "write_file"
    assert invalid["error"] == "malformed arguments"
    assert invalid["args"]["chars"] > 0
    assert invalid["args"]["sha256"]
    assert "E:" in invalid["args"]["head"]
